config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :articles
  resources :users

  root 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  CATEGORIES =     [
    ['Computer Programming', 'computer_programming'],
    ['Vacation', 'vacation']
  ]

  belongs_to :user
  validates :category, inclusion: { in: CATEGORIES.collect{|cat| cat[1]}, message: "%{value} is not a valid category" }, allow_blank: false
end

app/models/top_n_articles.rb
class TopNArticles < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  VALID_ROLES = ["admin", "editor", "user"]

  validates :role, inclusion: { in: VALID_ROLES, message: "%{value} is not a valid role" }, allow_blank: false
  after_initialize :set_default_role, :if => :new_record?

  def admin?
    role == "admin"
  end

  def editor?
    role == "editor"
  end

  def set_default_role
    self.role ||= "user"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit

    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    private
  
    def user_not_authorized
      flash[:alert] = "You are not authorized to perform this action."
      redirect_to(request.referrer || root_path)
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :update, :show, :create]

  # GET /articles
  # GET /articles.json
  def index
    if current_user
      @articles = Article.all
    else
      @articles = TopNArticles.where("RN <= ?", 3)
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
    authorize @article, :edit?
  end

  # POST /articles
  # POST /articles.json
  def create

    authorize User, :create_article?

    @article = Article.new(article_params)
    @article.user = current_user

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    authorize @article, :destroy?
    
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.eager_load(:user).find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :content, :category)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index]

  def index
    authorize User, :index?
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.select :category, options_for_select(Article::CATEGORIES, selected: form.object.category) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Category</th>
      <th colspan="3">&nbsp;</th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
    <% article = article.becomes(Article) %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.category %></td>
        <td><%= link_to 'Show', article %></td>
        <td>
          <% if policy(article).edit? %>
            <%= link_to 'Edit', edit_article_path(article) %>
          <% end %>
          </td>
        <td>
          <% if policy(article).destroy? %>
            <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<br>
<% if policy(:user).create_article? %>
    <%= link_to 'New Article', new_article_path %>
<% elsif %>
   You must be an editor to add a new article.
   <%= link_to 'Sign In', user_session_path unless current_user %>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.haml
%div
    %p{:id =>"notice"}
    %strong Title
    %p=@article.title

    %strong Content
    %p=@article.content

    %strong Category
    %p=@article.category

    %strong User
    %p=@article.user.email

    -if policy(@article).edit?
        =link_to 'Edit', edit_article_path(@article)
    =link_to 'Back', articles_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TonyRorCompetencyTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <% if !flash.empty? %>
      <div id="flash"> 
          <% flash.keys.each do |k| %> 
              <div class="<%= k %>">
                  <%= flash[k] %>
              </div>  
          <% end %>   
      </div>
  <% end %>

    <% if user_signed_in? %>
      <div>Signed in as: <%= current_user.email %> (<%= current_user.role %>) - <%= link_to 'Sign out', destroy_user_session_path, method: :delete %></div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Role</th>
      <th colspan="1">&nbsp;</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
      </tr>
    <% end %>
  </tbody>
</table>